apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: web-fingerprint-scanning-
spec:
  entrypoint: main
  volumes:
    - name: shared-output
      persistentVolumeClaim:
        claimName: shared-pvc
  arguments:
    parameters:
      - name: base-url
        value: 'http://10.43.113.255:8001'

  templates:
    - name: main
      steps:
        - - name: execute-wappalyzer
            templateRef:
              name: wappalyzer-template
              template: wappalyzer
            arguments:
              parameters:
                - name: base-url
                  value: "{{workflow.parameters.base-url}}"
