apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: docker-registry-deploy
spec:
  entrypoint: deploy-registry
  templates:
  - name: deploy-registry
    steps:
    - - name: create-deployment
        template: kubectl-apply
        arguments:
          artifacts:
          - name: manifest
            raw:
              data: |
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: registry
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: registry
                  template:
                    metadata:
                      labels:
                        app: registry
                    spec:
                      containers:
                      - name: registry
                        image: registry:2
                        ports:
                        - containerPort: 5000
    - - name: create-service
        template: kubectl-apply
        arguments:
          artifacts:
          - name: manifest
            raw:
              data: |
                apiVersion: v1
                kind: Service
                metadata:
                  name: registry
                spec:
                  type: NodePort
                  selector:
                    app: registry
                  ports:
                    - protocol: TCP
                      port: 5000
                      targetPort: 5000
                      nodePort: 30000

  - name: kubectl-apply
    inputs:
      artifacts:
      - name: manifest
        path: /tmp/manifest.yaml
    container:
      image: bitnami/kubectl
      command: [sh, -c]
      args: ["kubectl apply -f /tmp/manifest.yaml"]
