apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nikto-template
spec:
  volumes:
    - name: shared-output
      persistentVolumeClaim:
        claimName: shared-pvc
  templates:
    - name: nikto
      inputs:
        parameters:
          - name: base-url
      steps:
        - - name: run-nikto-self
            template: nikto-self
            arguments:
              parameters:
                - name: base-url
                  value: "{{inputs.parameters.base-url}}"
        - - name: run-nikto-parser
            template: nikto-parser
        - - name: run-nikto-uploader
            template: nikto-uploader
            arguments:
              parameters:
                - name: base-url
                  value: "{{inputs.parameters.base-url}}"

    - name: nikto-self
      inputs:
        parameters:
          - name: base-url
      container:
        image: astroicers/nikto
        command: [sh, -c]
        args:
          [
            "nikto.pl -h {{inputs.parameters.base-url}} -o /mnt/output/nikto.json -Format json || true",
          ]
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output
        securityContext:
          runAsUser: 0
          privileged: true

    - name: nikto-parser
      script:
        image: python:3.12.1-alpine3.19
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output
        command: [python]
        source: |
          with open('/mnt/output/nikto.json', 'r') as reader:
              file_contents = reader.read()

          with open('/mnt/output/nikto-parsed.json', 'w') as writer:
              writer.write(file_contents)

          print("File has been successfully read and written.")

    - name: nikto-uploader
      inputs:
        parameters:
          - name: base-url
      script:
        image: astroicers/dark-nebula-uploader
        command: [python]
        source: |
          import redis
          import json
          from datetime import datetime

          r = redis.Redis(host='redis', port=6379, db=0)

          with open('/mnt/output/nikto-parsed.json', 'r') as file:
              json_str = file.read()

          file_content = {}
          file_content['output'] = json.loads(json_str)
          key_name = "{{pod.name}}"

          file_content['timestamp'] = datetime.now().strftime("%Y%m%d%H%M%S")
          file_content['workflow'] = "{{workflow.name}}"
          file_content['pod'] = "{{pod.name}}"
          file_content['input'] = '{{inputs.parameters.base-url}}'
          file_content['type'] = "base-url-nikto"
          json_str_updated = json.dumps(file_content)

          r.set(key_name, json_str_updated)
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output
