apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: main-workflow
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: execute-whois
        templateRef:
          name: whois-template
          template: whois
        arguments:
          parameters:
          - name: domain
            value: "google.com"
