apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-access-role
rules:
- apiGroups: ["argoproj.io", ""]
  resources: ["pods", "services", "configmaps", "secrets", "workflowtemplates"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
