apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-access-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-service-account
  namespace: default
roleRef:
  kind: Role
  name: api-access-role
  apiGroup: rbac.authorization.k8s.io
