apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: subdomain-enumeration-
spec:
  entrypoint: main
  volumes:
    - name: shared-output
      persistentVolumeClaim:
        claimName: shared-pvc
  arguments:
    parameters:
      - name: base-domain
        value: "ecloudvalley.com"

  templates:
    - name: main
      steps:
        - - name: execute-subfinder
            templateRef:
              name: subfinder-template
              template: subfinder
            arguments:
              parameters:
                - name: base-domain
                  value: "{{workflow.parameters.base-domain}}"
          - name: execute-assetfinder
            templateRef:
              name: assetfinder-template
              template: assetfinder
            arguments:
              parameters:
                - name: base-domain
                  value: "{{workflow.parameters.base-domain}}"
          - name: execute-crt-sh
            templateRef:
              name: crt-sh-template
              template: crt-sh
            arguments:
              parameters:
                - name: base-domain
                  value: "{{workflow.parameters.base-domain}}"
        - - name: subdomain-enumeration-combiner
            templateRef:
              name: subdomain-enumeration-combiner-template
              template: subdomain-enumeration-combiner