apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: subfinder-template
spec:
  templates:
  - name: subfinder
    inputs:
      parameters:
      - name: base-domain
    container:
      image: astroicers/subfinder
      command: ["subfinder"]
      args: ["-silent","-d","{{inputs.parameters.base-domain}}"]
