apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: subfinder-template
spec:
  volumes:
    - name: shared-output
      persistentVolumeClaim:
        claimName: shared-pvc
  templates:
    - name: subfinder
      inputs:
        parameters:
          - name: base-domain
      steps:
        - - name: run-subfinder-self
            template: subfinder-self
            arguments:
              parameters:
                - name: base-domain
                  value: "{{inputs.parameters.base-domain}}"
        - - name: run-subfinder-parser
            template: subfinder-parser
        - - name: run-subfinder-uploader
            template: subfinder-uploader
            arguments:
              parameters:
                - name: base-domain
                  value: "{{inputs.parameters.base-domain}}"
      
    - name: subfinder-self
      inputs:
        parameters:
        - name: base-domain
      container:
        image: astroicers/subfinder
        command: [sh, -c]
        args: ["subfinder -silent -d {{inputs.parameters.base-domain}} > /mnt/output/subfinder.txt"]
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output

    - name: subfinder-parser
      script:
        image: python:3.12.1-alpine3.19
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output
        command: [python]
        source: |
          import re
          import json

          def extract_domains(file_path):
              with open(file_path, 'r') as file:
                  content = file.read()
                  pattern = r'\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}\b'
                  return set(re.findall(pattern, content, re.IGNORECASE))

          def save_domains_as_json(domains, output_file_path):
              with open(output_file_path, 'w') as file:
                  json_data = {"domains": list(domains)}
                  json.dump(json_data, file, indent=4)

          def main():
              input_file_path = '/mnt/output/subfinder.txt'
              output_file_path = '/mnt/output/subfinder-parsed.json'
              domains = extract_domains(input_file_path)
              save_domains_as_json(domains, output_file_path)

          if __name__ == "__main__":
              main()
      
    - name: subfinder-uploader
      inputs:
        parameters:
          - name: base-domain
      script:
        image: astroicers/dark-nebula-uploader
        command: [python]
        source: |
          import redis
          import json
          from datetime import datetime

          r = redis.Redis(host='redis', port=6379, db=0)

          with open('/mnt/output/subfinder-parsed.json', 'r') as file:
              json_str = file.read()

          file_content = json.loads(json_str)
          key_name = "{{pod.name}}"
          
          file_content['timestamp'] = datetime.now().strftime("%Y%m%d%H%M%S")
          file_content['workflow'] = "{{workflow.name}}"
          file_content['pod'] = "{{pod.name}}"
          file_content['input'] = "{{inputs.parameters.base-domain}}"
          file_content['tool'] = "subfinder"
          file_content['type'] = "subdomain-enumeration"
          file_content['output'] = {}
          file_content['output']['domains'] = file_content['domains']
          del file_content['domains']
          json_str_updated = json.dumps(file_content)

          r.set(key_name, json_str_updated)
        volumeMounts:
          - name: shared-output
            mountPath: /mnt/output
