apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: whois-template
spec:
  templates:
  - name: whois
    inputs:
      parameters:
      - name: base-domain
    container:
      image: localhost:30000/whois-local
      command: ["whois"]
      args: ["{{inputs.parameters.base-domain}}"]
