apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dark-nebula-domain
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: domain
      value: "google.com"

  templates:
  - name: main
    steps:
    - - name: execute-whois
        templateRef:
          name: whois-template
          template: whois
        arguments:
          parameters:
          - name: domain
            value: "{{workflow.parameters.domain}}"
      - name: execute-subfinder
        templateRef:
          name: subfinder-template
          template: subfinder
        arguments:
          parameters:
          - name: domain
            value: "{{workflow.parameters.domain}}"